# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01ab6acc725791808f745581f02a4165b632e4e8b3ed8a151c66a24f113c9c8b8e6857438ba2c1f8eba4325bd268b6d4a41331bbbadbc807e32239a1936da82d

test:
  secret_key_base: 8d9f7347b85954a02e7be87341e65c75a009f33815204f958a9f3fb96c85900f5308ee79c7092245ba0a1a910e6cb80de021ed331c6b1a02e3ae5d4119086bf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
